version: '2.1'
services:
  tomcat:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        TOMCAT_VERSION: ${TOMCAT_VERSION:-9}
        TOMCAT_JDK: ${TOMCAT_JDK:-jdk11}
    ports:
      - ${TOMCAT_HTTP_PORT:-8081}:8080
    volumes:
      - ./WEB-INF:/usr/local/tomcat/webapps/ROOT/WEB-INF
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml

